"""remove course columns add shots and update columns

Revision ID: 8e62fe3761eb
Revises: f498ca43cd18
Create Date: 2025-08-31 09:55:03.569939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e62fe3761eb'
down_revision = 'f498ca43cd18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stroke_number', sa.Integer(), nullable=True),
    sa.Column('start_distance', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('penalty', sa.Integer(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('round_hole_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_hole_id'], ['round_holes.id'], name=op.f('fk_shots_round_hole_id_round_holes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shots'))
    )

    with op.batch_alter_table('round_holes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_round_holes_course_hole_id_course_holes'), type_='foreignkey')

        batch_op.add_column(sa.Column('par', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.alter_column('hole_number',
               existing_type=sa.INTEGER(),
               nullable=False)

        batch_op.drop_column('surface')
        batch_op.drop_column('course_hole_id')
        batch_op.drop_column('penalty')
        batch_op.drop_column('start_distance')
            
    op.drop_table('course_holes')
    
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rounds_course_id_courses'), type_='foreignkey')

        batch_op.add_column(sa.Column('course_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('course_external_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tee', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tee_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('holes', sa.String(), nullable=True))
        
        batch_op.drop_constraint(batch_op.f('fk_rounds_user_id_users'), type_='foreignkey')
        
        batch_op.create_foreign_key(batch_op.f('fk_rounds_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

        batch_op.drop_column('tee_box')
        batch_op.drop_column('course_id')

        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        
    op.drop_table('courses')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(), nullable=False))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('display_name')

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tee_box', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_rounds_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rounds_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_rounds_course_id_courses'), 'courses', ['course_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('holes')
        batch_op.drop_column('tee_name')
        batch_op.drop_column('tee')
        batch_op.drop_column('course_external_id')
        batch_op.drop_column('course_name')

    with op.batch_alter_table('round_holes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_distance', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('penalty', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('course_hole_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('surface', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_round_holes_course_hole_id_course_holes'), 'course_holes', ['course_hole_id'], ['id'])
        batch_op.alter_column('hole_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('score')
        batch_op.drop_column('par')

    op.create_table('course_holes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_hole_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('par', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('yardage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_holes_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_holes'))
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('par_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_yards', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('holes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('slope_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.drop_table('shots')
    # ### end Alembic commands ###
